version: "3.8"

services: 

  openresty:
    image: openresty/openresty:alpine
    volumes: 
      - "./conf/openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./logs/openresty:/usr/local/openresty/nginx/logs"
      - "./certs:/usr/local/openresty/nginx/certs"
      - "./public:/www/public"
    network_mode: host

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_DATABASE: isucondition
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
      